# Generated by Django 4.0.6 on 2022-07-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_content_comment_comment_remove_comment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
