# Generated by Django 4.0.6 on 2022-07-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_comment_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
